module.exports = [
  {
    id: 0,
    title: 'failing test 1 etailed failure analysis',
    content: 'CORRECTIVE ACTION Recommended Corrective Action: detailed failure analysis -> We discovered that deep down within code that we were calling, an error debugging GUI was being displayed which ran in another thread.'
  },
  {
    id: 1,
    title: 'failing test 2 -verbose enabled.',
    content: 'have finally managed to get the failure to happen with -verbose enabled.'
  },
  {
    id: 2,
    title: 'failing test 3 detailed failure analysis',
    content:'CORRECTIVE ACTION Recommended Corrective Action: detailed failure analysis -> Line 58 is the line that the junit task is on that is failing'
  },
  {
    id: 3,
    title: 'failing test 4 problem with approach',
    content: 'CORRECTIVE ACTION Recommended Corrective Action: detailed failure analysis -> The problem with approach  is that they invariably end the test once the exception has been thrown'
  },
  {
    id: 4,
    title: 'failing test 5 need wo different tests',
    content: 'CORRECTIVE ACTION Recommended Corrective Action: detailed failure analysis -> need wo different tests- one for the exception and one to verify interaction with your mock'
  },
]
